safe: false
lsi: false
highlighter: rouge
exclude:
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - README.md
markdown: kramdown
redcarpet:
    extensions:
        - "no_intra_emphasis"
        - "fenced_code_blocks"
        - "autolink"
        - "tables"
        - "with_toc_data"
url: "http://envirocar.github.io/enviroCar-server"
